pool:
  vmImage: 'windows-latest'

variables:
  PYTHON_VERSION: 3.5

jobs:
- template: azure_templates/run-test.yml
  parameters:
    name: 'UnitTests_a'
    PYTHON_VERSION: $(PYTHON_VERSION)
    GLOB: 'a*'
