pool:
  vmImage: 'windows-latest'

variables:
  PYTHON_VERSION: 3.5

jobs:
- template: azure_templates/run-test.yml
  parameters:
    name: 'UnitTests_a_d'
    PYTHON_VERSION: $(PYTHON_VERSION)
    GLOB: '[a-d]*'
- template: azure_templates/run-test.yml
  parameters:
    name: 'UnitTests_e_h'
    PYTHON_VERSION: $(PYTHON_VERSION)
    GLOB: '[e-h]*'
- template: azure_templates/run-test.yml
  parameters:
    name: 'UnitTests_i_lo'
    PYTHON_VERSION: $(PYTHON_VERSION)
    GLOB: '[i-lo]*'
- template: azure_templates/run-test.yml
  parameters:
    name: 'UnitTests_lp_lz'
    PYTHON_VERSION: $(PYTHON_VERSION)
    GLOB: '[lp-lz]*'
- template: azure_templates/run-test.yml
  parameters:
    name: 'UnitTests_m_r'
    PYTHON_VERSION: $(PYTHON_VERSION)
    GLOB: '[m-r]*'
- template: azure_templates/run-test.yml
  parameters:
    name: 'UnitTests_sa'
    PYTHON_VERSION: $(PYTHON_VERSION)
    GLOB: 'sa*'
- template: azure_templates/run-test.yml
  parameters:
    name: 'UnitTests_sb_z'
    PYTHON_VERSION: $(PYTHON_VERSION)
    GLOB: '[sb-z]*'
- template: azure_templates/run-test.yml
  parameters:
    name: 'UnitTests_determinism'
    PYTHON_VERSION: $(PYTHON_VERSION)
    GLOB: '0deterministic.py'
